services:
    app-prod-1:
        image: money-keeper-client-v2/prod:${TAG:-latest}
        build: .
        ports:
            - '${HOST_PORT:-3000}:3000'
        env_file:
            - .env
        environment:
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
        # command: yarn start
        restart: unless-stopped
        deploy:
        mem_limit: 2g # Set max memory to 2 GB
        cpus: 2 # Set max CPU to 2 CPU core
